language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

services:
  - postgresql

script:
  - mvn test -B
  - mvn test -B -Dpersistence-provider=eclipselink
  - mvn test -B -Ddb=pg
  - mvn test -B -Ddb=pg -Dpersistence-provider=eclipselink

deploy:
  provider: script
  script: mvn deploy -s settings.xml -B -Dbintray=$bintray -DskipTests
  on:
    tags: true