language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

services:
  - postgresql

script:
  - mvn test -s settings.xml -B -Ddb=hsql
  - mvn test -s settings.xml -B -Ddb=pg

deploy:
  provider: script
  script: mvn deploy -s settings.xml -B -Dbintray=$bintray -DskipTests
  on:
    branch: master